# Case Study 2
## Analysis of US Births Dataset (2000–2014)

Name: Rehmat Tadpatri
USN: 2BL22CI066
Course: Data Analysis using Python

## Problem Statement

This case study analyzes the US Births dataset (2000–2014) obtained from the Social Security Administration (SSA). The objective is to investigate patterns in daily birth counts across different days of the week and throughout the year.The goal is to identify statistical trends, variability, and distribution characteristics in birth data while handling irregular observations.

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## Loading the Dataset
The dataset US_births_2000–2014_SSA.csv is loaded for analysis.

# Data Cleaning

In [3]:
df = pd.read_csv("US_births_2000-2014_SSA.csv")
df.head()

   year  month  date_of_month  day_of_week   births        date
0  2000      1            1.0            6   9083.0  01-01-2000
1  2000      1            2.0            7   8006.0  01-02-2000
2  2000      1            3.0            1  11363.0  01-03-2000
3  2000      1            4.0            2  13032.0  01-04-2000
4  2000      1            5.0            3  12558.0  01-05-2000

In [7]:
# to check dataset information
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5479 entries, 0 to 5478
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   year           5479 non-null   int64
 1   month          5479 non-null   int64
 2   date_of_month  5478 non-null   float64
 3   day_of_week    5479 non-null   int64
 4   births         5465 non-null   float64
 5   date           5479 non-null   object
dtypes: float64(2), int64(3), object(1)
memory usage: 257.0+ KB

              year        month  date_of_month  day_of_week        births
count  5479.000000  5479.000000    5478.000000  5479.000000   5465.000000
mean   2006.999270     6.522723      15.727455     3.999817  11348.814456
std       4.321085     3.449075       8.799535     2.000502   2327.445105
min    2000.000000     1.000000       1.000000     1.000000   5728.000000
25%    2003.000000     4.000000       8.000000     2.000000   8739.000000
50%    2007.000000     7.000000      16.000000     4.000000  12343.000000
75%    2011.000000    10.000000      23.000000     6.000000  13083.000000
max    2014.000000    12.000000      31.000000     7.000000  16081.000000

In [8]:
# Check data types
df.dtypes

year               int64
month              int64
date_of_month    float64
day_of_week        int64
births           float64
date              object
dtype: object

In [10]:
# Summary statistics
df.describe()

              year        month  date_of_month  day_of_week        births
count  5479.000000  5479.000000    5478.000000  5479.000000   5465.000000
mean   2006.999270     6.522723      15.727455     3.999817  11348.814456
std       4.321085     3.449075       8.799535     2.000502   2327.445105
min    2000.000000     1.000000       1.000000     1.000000   5728.000000
25%    2003.000000     4.000000       8.000000     2.000000   8739.000000
50%    2007.000000     7.000000      16.000000     4.000000  12343.000000
75%    2011.000000    10.000000      23.000000     6.000000  13083.000000
max    2014.000000    12.000000      31.000000     7.000000  16081.000000

In [11]:
# Check missing values
df.isnull().sum()

year              0
month             0
date_of_month     1
day_of_week       0
births           14
date              0
dtype: int64

In [12]:
# Check duplicate rows
df.duplicated().sum()

np.int64(0)