In [18]:
#LOAD DATASET
import pandas as pd
df=pd.read_csv('US_births_2000-2014_SSA.csv')
df

      year  month  date_of_month  day_of_week  births        date
0     2000      1              1            6    9083  01/01/2000
1     2000      1              2            7    8006  01/02/2000
2     2000      1              3            1   11363  01/03/2000
3     2000      1              4            2   13032  01/04/2000
4     2000      1              5            3   12558  01/05/2000
...    ...    ...            ...          ...     ...         ...
5474  2014     12             27            6    8656  12/27/2014
5475  2014     12             28            7    7724  12/28/2014
5476  2014     12             29            1   12811  12/29/2014
5477  2014     12             30            2   13634  12/30/2014
5478  2014     12             31            3   11990  12/31/2014

[5479 rows x 6 columns]

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5479 entries, 0 to 5478
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   year           5479 non-null   int64
 1   month          5479 non-null   int64
 2   date_of_month  5479 non-null   int64
 3   day_of_week    5479 non-null   int64
 4   births         5479 non-null   int64
 5   date           5479 non-null   object
dtypes: int64(5), object(1)
memory usage: 257.0+ KB

In [20]:
df.shape

(5479, 6)

In [21]:
df.columns

Index(['year', 'month', 'date_of_month', 'day_of_week', 'births', 'date'], dtype='object')

In [22]:
df.describe()

              year        month  date_of_month  day_of_week        births
count  5479.000000  5479.000000    5479.000000  5479.000000   5479.000000
mean   2006.999270     6.522723      15.730243     3.999817  11350.068261
std       4.321085     3.449075       8.801151     2.000502   2325.821049
min    2000.000000     1.000000       1.000000     1.000000   5728.000000
25%    2003.000000     4.000000       8.000000     2.000000   8740.000000
50%    2007.000000     7.000000      16.000000     4.000000  12343.000000
75%    2011.000000    10.000000      23.000000     6.000000  13082.000000
max    2014.000000    12.000000      31.000000     7.000000  16081.000000

In [23]:
df.index

RangeIndex(start=0, stop=5479, step=1)

In [24]:
df.dtypes

year              int64
month             int64
date_of_month     int64
day_of_week       int64
births            int64
date             object
dtype: object

In [25]:
df[df["year"].isnull()|df["month"].isnull()|df["date_of_month"].isnull()|df["day_of_week"].isnull()|df["date"].isnull()|df["births"].isnull()]

Empty DataFrame
Columns: [year, month, date_of_month, day_of_week, births, date]
Index: []

In [26]:
df.duplicated('year').any()

np.True_

In [27]:
sum(df.duplicated('year'))

5464

ANOTHER DATASET

In [28]:
#LOAD DATASET
import pandas as pd
df=pd.read_csv('movie_metadata.csv')
df

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5038,Color,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy|Drama,...,6.0,English,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84
5039,Color,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,...,359.0,English,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000
5040,Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,...,3.0,English,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16
5041,Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,...,9.0,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660
5042,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,...,84.0,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5043 entries, 0 to 5042
Data columns (total 28 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   color                      5024 non-null   object
 1   director_name              4939 non-null   object
 2   num_critic_for_reviews     4993 non-null   float64
 3   duration                   5028 non-null   float64
 4   director_facebook_likes    4939 non-null   float64
 5   actor_3_facebook_likes     5020 non-null   float64
 6   actor_2_name               5030 non-null   object
 7   actor_1_facebook_likes     5036 non-null   float64
 8   gross                      4159 non-null   float64
 9   genres                     5043 non-null   object
 10  actor_1_name               5036 non-null   object
 11  movie_title                5043 non-null   object
 12  num_voted_users            5043 non-null   int64
 13  cast_total_facebook_likes  5043 non-null   int64
 14  actor_3_name               5020 non-null   object
 15  facenumber_in_poster       5030 non-null   float64
 16  plot_keywords              4890 non-null   object
 17  movie_imdb_link            5043 non-null   object
 18  num_user_for_reviews       5022 non-null   float64
 19  language                   5029 non-null   object
 20  country                    5038 non-null   object
 21  content_rating             4740 non-null   object
 22  budget                     4551 non-null   float64
 23  title_year                 4935 non-null   float64
 24  actor_2_facebook_likes     5030 non-null   float64
 25  imdb_score                 5043 non-null   float64
 26  aspect_ratio               4714 non-null   float64
 27  movie_facebook_likes       5043 non-null   int64
dtypes: float64(13), int64(3), object(12)
memory usage: 1.1+ MB

In [30]:
df.shape

(5043, 28)

In [31]:
df.columns

Index(['color', 'director_name', 'num_critic_for_reviews', 'duration',
       'director_facebook_likes', 'actor_3_facebook_likes', 'actor_2_name',
       'actor_1_facebook_likes', 'gross', 'genres', 'actor_1_name',
       'movie_title', 'num_voted_users', 'cast_total_facebook_likes',
       'actor_3_name', 'facenumber_in_poster', 'plot_keywords',
       'movie_imdb_link', 'num_user_for_reviews', 'language', 'country',
       'content_rating', 'budget', 'title_year', 'actor_2_facebook_likes',
       'imdb_score', 'aspect_ratio', 'movie_facebook_likes'],
      dtype='object')

In [32]:
df.describe()

,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_1_facebook_likes,gross,num_voted_users,cast_total_facebook_likes,facenumber_in_poster,num_user_for_reviews,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
count,4993.000000,5028.000000,4939.000000,5020.000000,5036.000000,4.159000e+03,5.043000e+03,5043.000000,5030.000000,5022.000000,4.551000e+03,4935.000000,5030.000000,5043.000000,4714.000000,5043.000000
mean,140.194272,107.201074,686.509212,645.009761,6560.047061,4.846841e+07,8.366816e+04,9699.063851,1.371173,272.770808,3.975262e+07,2002.470517,1651.754473,6.442138,2.220403,7525.964505
std,121.601675,25.197441,2813.328607,1665.041728,15020.759120,6.845299e+07,1.384853e+05,18163.799124,2.013576,377.982886,2.061149e+08,12.474599,4042.438863,1.125116,1.385113,19320.445110
min,1.000000,7.000000,0.000000,0.000000,0.000000,1.620000e+02,5.000000e+00,0.000000,0.000000,1.000000,2.180000e+02,1916.000000,0.000000,1.600000,1.180000,0.000000
25%,50.000000,93.000000,7.000000,133.000000,614.000000,5.340988e+06,8.593500e+03,1411.000000,0.000000,65.000000,6.000000e+06,1999.000000,281.000000,5.800000,1.850000,0.000000
50%,110.000000,103.000000,49.000000,371.500000,988.000000,2.551750e+07,3.435900e+04,3090.000000,1.000000,156.000000,2.000000e+07,2005.000000,595.000000,6.600000,2.350000,166.000000
75%,195.000000,118.000000,194.500000,636.000000,11000.000000,6.230944e+07,9.630900e+04,13756.500000,2.000000,326.000000,4.500000e+07,2011.000000,918.000000,7.200000,2.350000,3000.000000
max,813.000000,511.000000,23000.000000,23000.000000,640000.000000,7.605058e+08,1.689764e+06,656730.000000,43.000000,5060.000000,1.221550e+10,2016.000000,137000.000000,9.500000,16.000000,349000.000000

In [33]:
df.dtypes

color                         object
director_name                 object
num_critic_for_reviews       float64
duration                     float64
director_facebook_likes      float64
actor_3_facebook_likes       float64
actor_2_name                  object
actor_1_facebook_likes       float64
gross                        float64
genres                        object
actor_1_name                  object
movie_title                   object
num_voted_users                int64
cast_total_facebook_likes      int64
actor_3_name                  object
facenumber_in_poster         float64
plot_keywords                 object
movie_imdb_link               object
num_user_for_reviews         float64
language                      object
country                       object
content_rating                object
budget                       float64
title_year                   float64
actor_2_facebook_likes       float64
imdb_score                   float64
aspect_ratio                 float64
movie_facebook_likes           int64
dtype: object

In [34]:
df[df["color"].isnull()|df["director_name"].isnull()|df["num_critic_for_reviews"].isnull()|df["duration"].isnull()|df["director_facebook_likes"].isnull()|df["actor_3_facebook_likes"].isnull()|df["actor_2_name"].isnull()|df["actor_1_facebook_likes"].isnull()|df["gross"].isnull()|df["genres"].isnull()|df["actor_1_name"].isnull()|df["movie_title"].isnull()|df["num_voted_users"].isnull()|df["cast_total_facebook_likes"].isnull()|df["actor_3_name"].isnull()|df["facenumber_in_poster"].isnull()|df["plot_keywords"].isnull()|df["movie_imdb_link"].isnull()|df["num_user_for_reviews"].isnull()|df["language"].isnull()|df["country"].isnull()|df["content_rating"].isnull()|df["budget"].isnull()|df["title_year"].isnull()|df["actor_2_facebook_likes"].isnull()|df["imdb_score"].isnull()|df["aspect_ratio"].isnull()|df["movie_facebook_likes"].isnull()]

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0
55,Color,Peter Sohn,298.0,93.0,113.0,113.0,Jack McGraw,275.0,123070338.0,Adventure|Animation|Comedy|Family|Fantasy,...,345.0,English,USA,PG,NaN,2015.0,150.0,6.8,2.35,20000
84,Color,Roland Joffé,10.0,109.0,596.0,283.0,Alice Englert,622.0,NaN,Action|Adventure|Romance|Sci-Fi,...,15.0,English,Belgium,R,NaN,2015.0,525.0,4.5,NaN,677
98,Color,Hideaki Anno,1.0,120.0,28.0,12.0,Shin'ya Tsukamoto,544.0,NaN,Action|Adventure|Drama|Horror|Sci-Fi,...,13.0,Japanese,Japan,NaN,NaN,2016.0,106.0,8.2,2.35,0
99,Color,Peter Jackson,645.0,182.0,0.0,773.0,Adam Brown,5000.0,303001229.0,Adventure|Fantasy,...,1367.0,English,USA,PG-13,180000000.0,2012.0,972.0,7.9,2.35,166000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5037,Color,Edward Burns,14.0,95.0,0.0,133.0,Caitlin FitzGerald,296.0,4584.0,Comedy|Drama,...,14.0,English,USA,Not Rated,9000.0,2011.0,205.0,6.4,NaN,413
5038,Color,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy|Drama,...,6.0,English,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84
5039,Color,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,...,359.0,English,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000
5040,Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,...,3.0,English,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16
5041,Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,...,9.0,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660

In [35]:
df.isnull().sum()

color                         19
director_name                104
num_critic_for_reviews        50
duration                      15
director_facebook_likes      104
actor_3_facebook_likes        23
actor_2_name                  13
actor_1_facebook_likes         7
gross                        884
genres                         0
actor_1_name                   7
movie_title                    0
num_voted_users                0
cast_total_facebook_likes      0
actor_3_name                  23
facenumber_in_poster          13
plot_keywords                153
movie_imdb_link                0
num_user_for_reviews          21
language                      14
country                        5
content_rating               303
budget                       492
title_year                   108
actor_2_facebook_likes        13
imdb_score                     0
aspect_ratio                 329
movie_facebook_likes           0
dtype: int64

In [36]:
nan_index=df[df["color"].isnull()|df["director_name"].isnull()|df["num_critic_for_reviews"].isnull()|df["duration"].isnull()|df["director_facebook_likes"].isnull()|df["actor_3_facebook_likes"].isnull()|df["actor_2_name"].isnull()|df["actor_1_facebook_likes"].isnull()|df["gross"].isnull()|df["genres"].isnull()|df["actor_1_name"].isnull()|df["movie_title"].isnull()|df["num_voted_users"].isnull()|df["cast_total_facebook_likes"].isnull()|df["actor_3_name"].isnull()|df["facenumber_in_poster"].isnull()|df["plot_keywords"].isnull()|df["movie_imdb_link"].isnull()|df["num_user_for_reviews"].isnull()|df["language"].isnull()|df["country"].isnull()|df["content_rating"].isnull()|df["budget"].isnull()|df["title_year"].isnull()|df["actor_2_facebook_likes"].isnull()|df["imdb_score"].isnull()|df["aspect_ratio"].isnull()|df["movie_facebook_likes"].isnull()].index

In [37]:
nan_index

Index([   4,   55,   84,   98,   99,  177,  199,  204,  206,  242,
       ...
       5030, 5031, 5032, 5034, 5036, 5037, 5038, 5039, 5040, 5041],
      dtype='int64', length=1288)

In [38]:
df.drop(nan_index,inplace=True)

In [39]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3755 entries, 0 to 5042
Data columns (total 28 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   color                      3755 non-null   object
 1   director_name              3755 non-null   object
 2   num_critic_for_reviews     3755 non-null   float64
 3   duration                   3755 non-null   float64
 4   director_facebook_likes    3755 non-null   float64
 5   actor_3_facebook_likes     3755 non-null   float64
 6   actor_2_name               3755 non-null   object
 7   actor_1_facebook_likes     3755 non-null   float64
 8   gross                      3755 non-null   float64
 9   genres                     3755 non-null   object
 10  actor_1_name               3755 non-null   object
 11  movie_title                3755 non-null   object
 12  num_voted_users            3755 non-null   int64
 13  cast_total_facebook_likes  3755 non-null   int64
 14  actor_3_name               3755 non-null   object
 15  facenumber_in_poster       3755 non-null   float64
 16  plot_keywords              3755 non-null   object
 17  movie_imdb_link            3755 non-null   object
 18  num_user_for_reviews       3755 non-null   float64
 19  language                   3755 non-null   object
 20  country                    3755 non-null   object
 21  content_rating             3755 non-null   object
 22  budget                     3755 non-null   float64
 23  title_year                 3755 non-null   float64
 24  actor_2_facebook_likes     3755 non-null   float64
 25  imdb_score                 3755 non-null   float64
 26  aspect_ratio               3755 non-null   float64
 27  movie_facebook_likes       3755 non-null   int64
dtypes: float64(13), int64(3), object(12)
memory usage: 850.7+ KB

In [40]:
df.isnull().sum()

color                        0
director_name                0
num_critic_for_reviews       0
duration                     0
director_facebook_likes      0
actor_3_facebook_likes       0
actor_2_name                 0
actor_1_facebook_likes       0
gross                        0
genres                       0
actor_1_name                 0
movie_title                  0
num_voted_users              0
cast_total_facebook_likes    0
actor_3_name                 0
facenumber_in_poster         0
plot_keywords                0
movie_imdb_link              0
num_user_for_reviews         0
language                     0
country                      0
content_rating               0
budget                       0
title_year                   0
actor_2_facebook_likes       0
imdb_score                   0
aspect_ratio                 0
movie_facebook_likes         0
dtype: int64

### *DAY 17*

In [41]:
#LOAD DATASET
import pandas as pd
df=pd.read_csv('US_births_2000-2014_SSA.csv')
df

      year  month  date_of_month  day_of_week  births        date
0     2000      1              1            6    9083  01/01/2000
1     2000      1              2            7    8006  01/02/2000
2     2000      1              3            1   11363  01/03/2000
3     2000      1              4            2   13032  01/04/2000
4     2000      1              5            3   12558  01/05/2000
...    ...    ...            ...          ...     ...         ...
5474  2014     12             27            6    8656  12/27/2014
5475  2014     12             28            7    7724  12/28/2014
5476  2014     12             29            1   12811  12/29/2014
5477  2014     12             30            2   13634  12/30/2014
5478  2014     12             31            3   11990  12/31/2014

[5479 rows x 6 columns]

In [42]:
df.head()

   year  month  date_of_month  day_of_week  births        date
0  2000      1              1            6    9083  01/01/2000
1  2000      1              2            7    8006  01/02/2000
2  2000      1              3            1   11363  01/03/2000
3  2000      1              4            2   13032  01/04/2000
4  2000      1              5            3   12558  01/05/2000

In [43]:
df.describe().sum()

year             17525.320355
month             5522.971798
date_of_month     5582.531394
day_of_week       5505.000319
births           75128.889310
dtype: float64

In [44]:
#null

df.isnull().sum()

year             0
month            0
date_of_month    0
day_of_week      0
births           0
date             0
dtype: int64

In [45]:
#manipulate

df[df["day_of_week"].isnull()]

Empty DataFrame
Columns: [year, month, date_of_month, day_of_week, births, date]
Index: []

In [46]:
import numpy as np

In [47]:
num_col = df.select_dtypes(include=np.number).columns

In [48]:
cat_col = df.select_dtypes(exclude=np.number).columns

In [49]:
for col in num_col:
    df[col].fillna(df[col].median(),inplace=True)

for col in cat_col:
    df[col].fillna(df[col].mode(),inplace=True)

C:\Users\MANJOORHUSEN\AppData\Local\Temp\ipykernel_19720\1412792612.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].median(),inplace=True)
C:\Users\MANJOORHUSEN\AppData\Local\Temp\ipykernel_19720\1412792612.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode(),inplace=True)

In [50]:
df.isnull().sum()

year             0
month            0
date_of_month    0
day_of_week      0
births           0
date             0
dtype: int64

In [51]:
df.duplicated().sum()

np.int64(0)

In [52]:
#outliers - data points wch live extremely 

outlier_summary={}

for col in num_col:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3-Q1

    #limits

    lower = Q1-1.5*IQR
    upper = Q3+1.5*IQR

    #Outlier
    outlier = df[(df[col]<lower)|(df[col]>upper)]

    outlier_summary[col]=len(outlier)

In [17]:
outlier_summary

{}