DAY 11&12

In [61]:
#load daataset
#LOAD DATASET
import pandas as pd
df=pd.read_csv('dirty_data.csv')
df

,Id,Timestamp,What is your gender?,What colour are your eyes?,"On average, how long does it take you to get from home to the University (in minutes)?",How tall are you (in cm)?
0,58,9/24/2018 15:31:57,Female,green,50,152
1,15,9/24/2018 22:44:36,Male,Black,40,175
2,34,9/25/2018 16:36:17,Male,Black,15,179
3,4,9/26/2018 1:25:27,Male,brown,27,180
4,69,9/26/2018 12:46:21,Male,Blue,NaN,175
...,...,...,...,...,...,...
81,52,10/01/2020 12:39,Female,blue,15,163
82,5,10/01/2020 16:48,Male,blue,15,180
83,35,10/02/2020 09:18,Female,Brown,90,165
84,54,10/07/2020 10:08,Male,Brown,10,180
85,5,10/08/2020 11:48,Male,Blue,apx. 120,183

In [62]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 86 entries, 0 to 85
Data columns (total 6 columns):
 #   Column                                                                                  Non-Null Count  Dtype
---  ------                                                                                  --------------  -----
 0   Id                                                                                      86 non-null     int64
 1   Timestamp                                                                               86 non-null     object
 2   What is your gender?                                                                    86 non-null     object
 3   What colour are your eyes?                                                              86 non-null     object
 4   On average, how long does it take you to get from home to the University (in minutes)?  82 non-null     object
 5   How tall are you (in cm)?                                                               85 non-null     object
dtypes: int64(1), object(5)
memory usage: 4.2+ KB

In [63]:
df.shape

(86, 6)

In [64]:
df.columns

Index(['Id', 'Timestamp', 'What is your gender?', 'What colour are your eyes?',
       'On average, how long does it take you to get from home to the University (in minutes)?',
       'How tall are you (in cm)?'],
      dtype='object')

In [65]:
df.describe()

              Id
count  86.000000
mean   32.604651
std    20.245132
min     0.000000
25%    19.000000
50%    32.000000
75%    47.000000
max    74.000000

In [66]:
df.index

RangeIndex(start=0, stop=86, step=1)

In [67]:
df.dtypes

Id                                                                                         int64
Timestamp                                                                                 object
What is your gender?                                                                      object
What colour are your eyes?                                                                object
On average, how long does it take you to get from home to the University (in minutes)?    object
How tall are you (in cm)?                                                                 object
dtype: object

In [68]:
columns = {
    'What is your gender?': 'gender',
    'What colour are your eyes?': 'eye_color',
    'On average, how long does it take you to get from home to the University (in minutes)?': 'commute_time',
    'How tall are you (in cm)?': 'height',
    'Timestamp': 'timestamp'
}

df.rename(columns=columns, inplace=True)
df

    Id           timestamp  gender eye_color commute_time height
0   58  9/24/2018 15:31:57  Female     green           50    152
1   15  9/24/2018 22:44:36    Male     Black           40    175
2   34  9/25/2018 16:36:17    Male     Black           15    179
3    4   9/26/2018 1:25:27    Male     brown           27    180
4   69  9/26/2018 12:46:21    Male      Blue          NaN    175
..  ..                 ...     ...       ...          ...    ...
81  52    10/01/2020 12:39  Female      blue           15    163
82   5    10/01/2020 16:48    Male      blue           15    180
83  35    10/02/2020 09:18  Female     Brown           90    165
84  54    10/07/2020 10:08    Male     Brown           10    180
85   5    10/08/2020 11:48    Male      Blue     apx. 120    183

[86 rows x 6 columns]

In [69]:
df[df["commute_time"].isnull()|df["height"].isnull()]

    Id           timestamp  gender eye_color commute_time height
4   69  9/26/2018 12:46:21    Male      Blue          NaN    175
9    0    10/03/2018 23:50  Female     Black           10    NaN
31  25    10/07/2018 22:32    Male     black          NaN    177
79  19    10/01/2020 01:45    Male    Black           NaN    163
80  22    10/01/2020 01:45    Male    Black           NaN    163

In [70]:
nan_index=df[df["commute_time"].isnull()|df["height"].isnull()].index

In [71]:
nan_index

Index([4, 9, 31, 79, 80], dtype='int64')

In [72]:
df.drop(nan_index,inplace=True)

In [73]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 81 entries, 0 to 85
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Id            81 non-null     int64
 1   timestamp     81 non-null     object
 2   gender        81 non-null     object
 3   eye_color     81 non-null     object
 4   commute_time  81 non-null     object
 5   height        81 non-null     object
dtypes: int64(1), object(5)
memory usage: 4.4+ KB

In [74]:
#in the above index is not reset...... we need to reset the index

In [75]:
#reset index

df.reset_index(drop=True,inplace=True)

In [76]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 81 entries, 0 to 80
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Id            81 non-null     int64
 1   timestamp     81 non-null     object
 2   gender        81 non-null     object
 3   eye_color     81 non-null     object
 4   commute_time  81 non-null     object
 5   height        81 non-null     object
dtypes: int64(1), object(5)
memory usage: 3.9+ KB

In [77]:
#Duplicate values

df.duplicated('Id').any()

np.True_

In [78]:
#for not getting np.true
bool(df.duplicated('Id').any())

True

In [79]:
sum(df.duplicated('Id'))

30

In [80]:
df.drop_duplicates('Id',keep='last',inplace=True,ignore_index=True)

In [81]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51 entries, 0 to 50
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Id            51 non-null     int64
 1   timestamp     51 non-null     object
 2   gender        51 non-null     object
 3   eye_color     51 non-null     object
 4   commute_time  51 non-null     object
 5   height        51 non-null     object
dtypes: int64(1), object(5)
memory usage: 2.5+ KB

In [82]:
df.duplicated('Id').any()

np.False_

In [83]:
df

,Id,timestamp,gender,eye_color,commute_time,height
0,58,9/24/2018 15:31:57,Female,green,50,152
1,34,9/25/2018 16:36:17,Male,Black,15,179
2,4,9/26/2018 1:25:27,Male,brown,27,180
3,73,10/01/2018 18:51,Female,Brown,10,157
4,49,10/03/2018 17:22,Male,Brown,20min,179.83cm
5,43,10/03/2018 23:51,Prefer not to say,borwn,1 hour,"6'4"""
6,56,10/03/2018 23:55,Non binary,Blueish,40mins,175
7,48,10/04/2018 06:34,Male,Green,35,"1,82"
8,28,10/04/2018 09:19,Male,Green,30,180.34
9,57,10/04/2018 10:03,Male,brown,10,173
10,67,10/04/2018 11:00,Male,Blue,15,178
11,15,10/04/2018 12:06,Female,Brown,40,158
12,65,10/04/2018 13:43,Male,black,20,177
13,66,10/04/2018 14:08,Female,green,30,170
14,12,10/04/2018 16:02,Male,brown,15,188
15,61,10/06/2018 16:01,Male,blue,32,175
16,3,10/09/2018 01:37,Male,brown,2.5 hrs,183
17,50,9/30/2019 14:31:41,Male,Brown,30,186
18,69,9/30/2019 14:31:48,Male,brown,20,175
19,14,10/01/2019 11:09,Female,brown,50,173
20,38,10/01/2019 13:25,Male,Hazel,15,175
21,8,10/16/2019 9:20:48,Female,brown,20,160
22,9,9/28/2020 22:39:35,Female,Brown,40 mins,157
23,40,9/29/2020 15:11:45,Male,brown,30,200
24,74,9/29/2020 17:57:05,Male,brown,50,175
25,21,9/30/2020 11:34:10,Male,Hazel,5,183
26,47,9/30/2020 12:08:29,Male,Hazel,60,162
27,26,9/30/2020 12:22:36,Male,brown,30,183
28,53,9/30/2020 12:55:57,Male,blue,30,189
29,36,9/30/2020 13:57:48,Female,black,120,162
30,7,9/30/2020 14:02:20,Male,Green,35,190cm
31,45,9/30/2020 14:07:08,Male,Green,40,190
32,10,9/30/2020 14:10:13,Female,brown,0,169
33,46,9/30/2020 15:07:19,Male,Green,35,190
34,19,9/30/2020 15:07:20,Male,Brown,50,176
35,33,9/30/2020 15:11:03,Male,brown,35,192
36,63,9/30/2020 15:12:58,Male,Brown,45,182
37,22,9/30/2020 15:17:53,Male,Black,3 when I live on campus,185
38,42,9/30/2020 15:32:21,Female,Dark brown,60,155
39,11,9/30/2020 15:35:26,Female,Hazel,30 minutes,164
40,0,9/30/2020 15:41:22,Male,Brown,20 minutes,183
41,23,9/30/2020 15:51:18,Male,Brown,30,200
42,20,9/30/2020 15:53:45,Female,brown,15,166
43,29,9/30/2020 16:39:07,Female,Green,20,166
44,25,9/30/2020 16:51:49,Male,Brown,30,173
45,31,9/30/2020 17:03:36,Female,Dark brown,I live on campus accommodation.,163
46,39,9/30/2020 17:35:05,Male,Brown,45,182
47,52,10/01/2020 12:39,Female,blue,15,163
48,35,10/02/2020 09:18,Female,Brown,90,165
49,54,10/07/2020 10:08,Male,Brown,10,180
50,5,10/08/2020 11:48,Male,Blue,apx. 120,183

DAY 13

In [84]:
df.timestamp=pd.to_datetime(df.timestamp,format='mixed')

In [85]:
df['date']=df.timestamp.dt.date
df['time']=df.timestamp.dt.time
df

,Id,timestamp,gender,eye_color,commute_time,height,date,time
0,58,2018-09-24 15:31:57,Female,green,50,152,2018-09-24,15:31:57
1,34,2018-09-25 16:36:17,Male,Black,15,179,2018-09-25,16:36:17
2,4,2018-09-26 01:25:27,Male,brown,27,180,2018-09-26,01:25:27
3,73,2018-10-01 18:51:00,Female,Brown,10,157,2018-10-01,18:51:00
4,49,2018-10-03 17:22:00,Male,Brown,20min,179.83cm,2018-10-03,17:22:00
5,43,2018-10-03 23:51:00,Prefer not to say,borwn,1 hour,"6'4""",2018-10-03,23:51:00
6,56,2018-10-03 23:55:00,Non binary,Blueish,40mins,175,2018-10-03,23:55:00
7,48,2018-10-04 06:34:00,Male,Green,35,"1,82",2018-10-04,06:34:00
8,28,2018-10-04 09:19:00,Male,Green,30,180.34,2018-10-04,09:19:00
9,57,2018-10-04 10:03:00,Male,brown,10,173,2018-10-04,10:03:00
10,67,2018-10-04 11:00:00,Male,Blue,15,178,2018-10-04,11:00:00
11,15,2018-10-04 12:06:00,Female,Brown,40,158,2018-10-04,12:06:00
12,65,2018-10-04 13:43:00,Male,black,20,177,2018-10-04,13:43:00
13,66,2018-10-04 14:08:00,Female,green,30,170,2018-10-04,14:08:00
14,12,2018-10-04 16:02:00,Male,brown,15,188,2018-10-04,16:02:00
15,61,2018-10-06 16:01:00,Male,blue,32,175,2018-10-06,16:01:00
16,3,2018-10-09 01:37:00,Male,brown,2.5 hrs,183,2018-10-09,01:37:00
17,50,2019-09-30 14:31:41,Male,Brown,30,186,2019-09-30,14:31:41
18,69,2019-09-30 14:31:48,Male,brown,20,175,2019-09-30,14:31:48
19,14,2019-10-01 11:09:00,Female,brown,50,173,2019-10-01,11:09:00
20,38,2019-10-01 13:25:00,Male,Hazel,15,175,2019-10-01,13:25:00
21,8,2019-10-16 09:20:48,Female,brown,20,160,2019-10-16,09:20:48
22,9,2020-09-28 22:39:35,Female,Brown,40 mins,157,2020-09-28,22:39:35
23,40,2020-09-29 15:11:45,Male,brown,30,200,2020-09-29,15:11:45
24,74,2020-09-29 17:57:05,Male,brown,50,175,2020-09-29,17:57:05
25,21,2020-09-30 11:34:10,Male,Hazel,5,183,2020-09-30,11:34:10
26,47,2020-09-30 12:08:29,Male,Hazel,60,162,2020-09-30,12:08:29
27,26,2020-09-30 12:22:36,Male,brown,30,183,2020-09-30,12:22:36
28,53,2020-09-30 12:55:57,Male,blue,30,189,2020-09-30,12:55:57
29,36,2020-09-30 13:57:48,Female,black,120,162,2020-09-30,13:57:48
30,7,2020-09-30 14:02:20,Male,Green,35,190cm,2020-09-30,14:02:20
31,45,2020-09-30 14:07:08,Male,Green,40,190,2020-09-30,14:07:08
32,10,2020-09-30 14:10:13,Female,brown,0,169,2020-09-30,14:10:13
33,46,2020-09-30 15:07:19,Male,Green,35,190,2020-09-30,15:07:19
34,19,2020-09-30 15:07:20,Male,Brown,50,176,2020-09-30,15:07:20
35,33,2020-09-30 15:11:03,Male,brown,35,192,2020-09-30,15:11:03
36,63,2020-09-30 15:12:58,Male,Brown,45,182,2020-09-30,15:12:58
37,22,2020-09-30 15:17:53,Male,Black,3 when I live on campus,185,2020-09-30,15:17:53
38,42,2020-09-30 15:32:21,Female,Dark brown,60,155,2020-09-30,15:32:21
39,11,2020-09-30 15:35:26,Female,Hazel,30 minutes,164,2020-09-30,15:35:26
40,0,2020-09-30 15:41:22,Male,Brown,20 minutes,183,2020-09-30,15:41:22
41,23,2020-09-30 15:51:18,Male,Brown,30,200,2020-09-30,15:51:18
42,20,2020-09-30 15:53:45,Female,brown,15,166,2020-09-30,15:53:45
43,29,2020-09-30 16:39:07,Female,Green,20,166,2020-09-30,16:39:07
44,25,2020-09-30 16:51:49,Male,Brown,30,173,2020-09-30,16:51:49
45,31,2020-09-30 17:03:36,Female,Dark brown,I live on campus accommodation.,163,2020-09-30,17:03:36
46,39,2020-09-30 17:35:05,Male,Brown,45,182,2020-09-30,17:35:05
47,52,2020-10-01 12:39:00,Female,blue,15,163,2020-10-01,12:39:00
48,35,2020-10-02 09:18:00,Female,Brown,90,165,2020-10-02,09:18:00
49,54,2020-10-07 10:08:00,Male,Brown,10,180,2020-10-07,10:08:00
50,5,2020-10-08 11:48:00,Male,Blue,apx. 120,183,2020-10-08,11:48:00

In [86]:
#drop the column

In [87]:
df.drop(columns='timestamp',inplace=True)

In [88]:
df

,Id,gender,eye_color,commute_time,height,date,time
0,58,Female,green,50,152,2018-09-24,15:31:57
1,34,Male,Black,15,179,2018-09-25,16:36:17
2,4,Male,brown,27,180,2018-09-26,01:25:27
3,73,Female,Brown,10,157,2018-10-01,18:51:00
4,49,Male,Brown,20min,179.83cm,2018-10-03,17:22:00
5,43,Prefer not to say,borwn,1 hour,"6'4""",2018-10-03,23:51:00
6,56,Non binary,Blueish,40mins,175,2018-10-03,23:55:00
7,48,Male,Green,35,"1,82",2018-10-04,06:34:00
8,28,Male,Green,30,180.34,2018-10-04,09:19:00
9,57,Male,brown,10,173,2018-10-04,10:03:00
10,67,Male,Blue,15,178,2018-10-04,11:00:00
11,15,Female,Brown,40,158,2018-10-04,12:06:00
12,65,Male,black,20,177,2018-10-04,13:43:00
13,66,Female,green,30,170,2018-10-04,14:08:00
14,12,Male,brown,15,188,2018-10-04,16:02:00
15,61,Male,blue,32,175,2018-10-06,16:01:00
16,3,Male,brown,2.5 hrs,183,2018-10-09,01:37:00
17,50,Male,Brown,30,186,2019-09-30,14:31:41
18,69,Male,brown,20,175,2019-09-30,14:31:48
19,14,Female,brown,50,173,2019-10-01,11:09:00
20,38,Male,Hazel,15,175,2019-10-01,13:25:00
21,8,Female,brown,20,160,2019-10-16,09:20:48
22,9,Female,Brown,40 mins,157,2020-09-28,22:39:35
23,40,Male,brown,30,200,2020-09-29,15:11:45
24,74,Male,brown,50,175,2020-09-29,17:57:05
25,21,Male,Hazel,5,183,2020-09-30,11:34:10
26,47,Male,Hazel,60,162,2020-09-30,12:08:29
27,26,Male,brown,30,183,2020-09-30,12:22:36
28,53,Male,blue,30,189,2020-09-30,12:55:57
29,36,Female,black,120,162,2020-09-30,13:57:48
30,7,Male,Green,35,190cm,2020-09-30,14:02:20
31,45,Male,Green,40,190,2020-09-30,14:07:08
32,10,Female,brown,0,169,2020-09-30,14:10:13
33,46,Male,Green,35,190,2020-09-30,15:07:19
34,19,Male,Brown,50,176,2020-09-30,15:07:20
35,33,Male,brown,35,192,2020-09-30,15:11:03
36,63,Male,Brown,45,182,2020-09-30,15:12:58
37,22,Male,Black,3 when I live on campus,185,2020-09-30,15:17:53
38,42,Female,Dark brown,60,155,2020-09-30,15:32:21
39,11,Female,Hazel,30 minutes,164,2020-09-30,15:35:26
40,0,Male,Brown,20 minutes,183,2020-09-30,15:41:22
41,23,Male,Brown,30,200,2020-09-30,15:51:18
42,20,Female,brown,15,166,2020-09-30,15:53:45
43,29,Female,Green,20,166,2020-09-30,16:39:07
44,25,Male,Brown,30,173,2020-09-30,16:51:49
45,31,Female,Dark brown,I live on campus accommodation.,163,2020-09-30,17:03:36
46,39,Male,Brown,45,182,2020-09-30,17:35:05
47,52,Female,blue,15,163,2020-10-01,12:39:00
48,35,Female,Brown,90,165,2020-10-02,09:18:00
49,54,Male,Brown,10,180,2020-10-07,10:08:00
50,5,Male,Blue,apx. 120,183,2020-10-08,11:48:00

In [89]:
pd.unique(df.eye_color)

array(['green', 'Black', 'brown', 'Brown', 'borwn', 'Blueish', 'Green ',
       'Green', 'Blue', 'black', 'blue', 'Hazel', 'Dark brown ',
       'Dark brown'], dtype=object)

In [90]:
print(df.eye_color.value_counts())

eye_color
brown          13
Brown          13
Green           5
Hazel           4
blue            3
green           2
Black           2
Blue            2
black           2
borwn           1
Blueish         1
Green           1
Dark brown      1
Dark brown      1
Name: count, dtype: int64

In [91]:
#modifying all the mispelled and different to one 

df.loc[df.eye_color == 'borwn' , 'eye_color'] = 'Brown'

In [92]:
print(df.eye_color.value_counts())

eye_color
Brown          14
brown          13
Green           5
Hazel           4
blue            3
green           2
Black           2
Blue            2
black           2
Blueish         1
Green           1
Dark brown      1
Dark brown      1
Name: count, dtype: int64

In [93]:
df.head(10)

,Id,gender,eye_color,commute_time,height,date,time
0,58,Female,green,50,152,2018-09-24,15:31:57
1,34,Male,Black,15,179,2018-09-25,16:36:17
2,4,Male,brown,27,180,2018-09-26,01:25:27
3,73,Female,Brown,10,157,2018-10-01,18:51:00
4,49,Male,Brown,20min,179.83cm,2018-10-03,17:22:00
5,43,Prefer not to say,Brown,1 hour,"6'4""",2018-10-03,23:51:00
6,56,Non binary,Blueish,40mins,175,2018-10-03,23:55:00
7,48,Male,Green,35,"1,82",2018-10-04,06:34:00
8,28,Male,Green,30,180.34,2018-10-04,09:19:00
9,57,Male,brown,10,173,2018-10-04,10:03:00

In [94]:
df.eye_color = df.eye_color.apply(lambda x: x.capitalize())
df.eye_color = df.eye_color.apply(lambda x: x.strip())

In [95]:
df

,Id,gender,eye_color,commute_time,height,date,time
0,58,Female,Green,50,152,2018-09-24,15:31:57
1,34,Male,Black,15,179,2018-09-25,16:36:17
2,4,Male,Brown,27,180,2018-09-26,01:25:27
3,73,Female,Brown,10,157,2018-10-01,18:51:00
4,49,Male,Brown,20min,179.83cm,2018-10-03,17:22:00
5,43,Prefer not to say,Brown,1 hour,"6'4""",2018-10-03,23:51:00
6,56,Non binary,Blueish,40mins,175,2018-10-03,23:55:00
7,48,Male,Green,35,"1,82",2018-10-04,06:34:00
8,28,Male,Green,30,180.34,2018-10-04,09:19:00
9,57,Male,Brown,10,173,2018-10-04,10:03:00
10,67,Male,Blue,15,178,2018-10-04,11:00:00
11,15,Female,Brown,40,158,2018-10-04,12:06:00
12,65,Male,Black,20,177,2018-10-04,13:43:00
13,66,Female,Green,30,170,2018-10-04,14:08:00
14,12,Male,Brown,15,188,2018-10-04,16:02:00
15,61,Male,Blue,32,175,2018-10-06,16:01:00
16,3,Male,Brown,2.5 hrs,183,2018-10-09,01:37:00
17,50,Male,Brown,30,186,2019-09-30,14:31:41
18,69,Male,Brown,20,175,2019-09-30,14:31:48
19,14,Female,Brown,50,173,2019-10-01,11:09:00
20,38,Male,Hazel,15,175,2019-10-01,13:25:00
21,8,Female,Brown,20,160,2019-10-16,09:20:48
22,9,Female,Brown,40 mins,157,2020-09-28,22:39:35
23,40,Male,Brown,30,200,2020-09-29,15:11:45
24,74,Male,Brown,50,175,2020-09-29,17:57:05
25,21,Male,Hazel,5,183,2020-09-30,11:34:10
26,47,Male,Hazel,60,162,2020-09-30,12:08:29
27,26,Male,Brown,30,183,2020-09-30,12:22:36
28,53,Male,Blue,30,189,2020-09-30,12:55:57
29,36,Female,Black,120,162,2020-09-30,13:57:48
30,7,Male,Green,35,190cm,2020-09-30,14:02:20
31,45,Male,Green,40,190,2020-09-30,14:07:08
32,10,Female,Brown,0,169,2020-09-30,14:10:13
33,46,Male,Green,35,190,2020-09-30,15:07:19
34,19,Male,Brown,50,176,2020-09-30,15:07:20
35,33,Male,Brown,35,192,2020-09-30,15:11:03
36,63,Male,Brown,45,182,2020-09-30,15:12:58
37,22,Male,Black,3 when I live on campus,185,2020-09-30,15:17:53
38,42,Female,Dark brown,60,155,2020-09-30,15:32:21
39,11,Female,Hazel,30 minutes,164,2020-09-30,15:35:26
40,0,Male,Brown,20 minutes,183,2020-09-30,15:41:22
41,23,Male,Brown,30,200,2020-09-30,15:51:18
42,20,Female,Brown,15,166,2020-09-30,15:53:45
43,29,Female,Green,20,166,2020-09-30,16:39:07
44,25,Male,Brown,30,173,2020-09-30,16:51:49
45,31,Female,Dark brown,I live on campus accommodation.,163,2020-09-30,17:03:36
46,39,Male,Brown,45,182,2020-09-30,17:35:05
47,52,Female,Blue,15,163,2020-10-01,12:39:00
48,35,Female,Brown,90,165,2020-10-02,09:18:00
49,54,Male,Brown,10,180,2020-10-07,10:08:00
50,5,Male,Blue,apx. 120,183,2020-10-08,11:48:00

In [96]:
print(df.eye_color.value_counts())

eye_color
Brown         27
Green          8
Blue           5
Black          4
Hazel          4
Dark brown     2
Blueish        1
Name: count, dtype: int64

DAY 14

In [97]:
#TO CHANGE THE DATATYPE

def update_commute_time(val):
    strips=['min','mins','minutes','hrs','hour']
    for substr in strips:
        if substr in val:
            split_index=val.find(substr)
            new_val=float(val[:split_index].strip())

            return new_val if substr =='min' else 60.0*new_val
        
    substr='apx.'
    if substr in val:
        split_index=val.find(substr)
        return float(val[split_index + len(substr):].strip())
        
    if "campus" in val:
        return 0
        
    return float(val)

In [98]:
df["commute_mins"] = df["commute_time"].apply(update_commute_time)

In [99]:
print(pd.unique(df.commute_mins))
#print(df.commute_mins)

[ 50.  15.  27.  10.  20.  60.  40.  35.  30.  32. 150.   5. 120.   0.
  45.  90.]

In [101]:
#lambda func 

age = lambda x : x>18
print(age(12))

False

In [102]:
#no lambda func
def age(x):
    if x>18:
        print('adult')
    else:
        print('minor')
age(12)

minor

In [103]:
#lambda func with print stmt 
check_age = lambda age: "Above 18" if age > 18 else "minor"
print(check_age(25)) 
print(check_age(15))

Above 18
minor

DAY 15

In [104]:
def update_height(val):
    substr = "cm"
    if substr in val:
        split_idx = val.find(substr)
        return float(val[:split_idx].strip())

    substr = "."
    if substr in val:
        if val.find(substr) == 1:
            return float(val) * 100.0
        return float(val)

    sunstr=","
    if substr in val:
        val = val.replace(substr,".")
        return float(val) * 100.0

    substr = "\'"
    if substr in val:
        split_strs = val.replace("\'"," ").replace("\""," ").split(" ")
        feet = float(split_strs[0])
        inches = float(split_strs[1])

        return 2.54 * inches + 30.48 * feet

        return float(val)

In [105]:
df.height = df.height.apply(update_height)
print(pd.unique(df.height))

[   nan 179.83 193.04 180.34 190.  ]

In [ ]:
#EDA